sudo: required

services:
  - docker

# Caching so the next build will be fast too.
cache:
  timeout: 600
  bundler: true
  directories:
  - $HOME/.stack
  - /var/lib/docker
  - $HOME/docker  #https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
  - $HOME/build/peterbecich/stock-stats/.stack-work

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

  # Load cached docker images
  # - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  
  - eval "$(ssh-agent -s)" #start the ssh agent

  - pwd

  - openssl aes-256-cbc -K $encrypted_b227e55ec8b3_key -iv $encrypted_b227e55ec8b3_iv -in travis_stats_secrets.tar.enc -out travis_stats_secrets.tar -d
  - tar xvf travis_stats_secrets.tar

  - chmod 600 travis_stats
  - ssh-add travis_stats
  
  - chmod 600 travis_stats_common
  - ssh-add travis_stats_common

  - chmod 600 travis_stats_push_github
  - ssh-add travis_stats_push_github

  - ls

  - git submodule update --init --recursive
  
  - docker pull fpco/stack-build:lts-10.3

  
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup
  - stack image container

  - df -h

script:
  - df -h
  - stack build
  - stack image container
  - df -h
  - export GIT_SSH_COMMAND='ssh -i $HOME/build/peterbecich/stock-stats/travis_common_push_github'
  - ./stock-ops/travis/merge.sh

# https://gist.github.com/petrbel/c3bf7e0f59c22a52f534
git:
  submodules: false

before_cache:
  # Save tagged docker images
  # - >
  #   mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
  #   | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
  
