sudo: required

services:
  - docker

# Caching so the next build will be fast too.
cache:
  timeout: 600
  directories:
  - $HOME/.stack
  - /var/lib/docker

before_install:
  - openssl aes-256-cbc -K $encrypted_b227e55ec8b3_key -iv $encrypted_b227e55ec8b3_iv -in travis_stats_common.enc -out travis_stats_common -d
  - chmod 600 travis_stats_common
  - eval "$(ssh-agent -s)" #start the ssh agent
  - ssh-add travis_stats_common
  - docker pull fpco/stack-build:lts-9.17

  - git submodule update --init --recursive
  
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup

script:
  #- stack build
  - stack image container


# https://gist.github.com/petrbel/c3bf7e0f59c22a52f534
git:
  submodules: false
