
# resolver: lts-9.17
resolver: lts-10.3

packages:
- .
- ./stock-common

extra-deps:
- yaml-config-0.4.0
# - stock-common-0.1.0.0

flags: {}

extra-package-dbs: []

# ghc-options:
#   "*": -j -threaded

# https://docs.haskellstack.org/en/stable/docker_integration/

docker:
  enable: true

  mount:
    - "stock-common:/usr/local/src/stock-common"
  
image:
  containers:
    -
      base: "fpco/stack-build:lts-10.3"
      name: "peterbecich/stock-stats"

      add:
        conf/: /usr/local/etc/
        stock-common/: /usr/local/src/stock-common/

